query GetAnamneses($status: AnamneseStatus) {
  getAnamneses(status: $status) {
    id
    firstName
    lastName
    dateOfBirth
    email
    status
    signatureConfirmed
  }
}

query GetAnamnese($id: String!) {
  getOneAnamnese(anamneseId: $id) {
    id
    firstName
    lastName
    dateOfBirth
    email
    status
    complaintsAndOnset
    workplaceAccident
    workplaceAccidentDetails
    primaryCarePhysician
    medications
    preExistingConditions {
      selected
      other
    }
    emailVerifiedAt
    signatureConfirmed
    availableActions
  }
}

mutation TransitionAnamneseStatus($anamneseId: String!, $action: AnamneseAction!) {
  transition(anamneseId: $anamneseId, action: $action) {
    id
    status
  }
}
