services: 
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    volumes:
      - ..:/workspaces/anamnesebogen:cached
    command: sleep infinity

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"